--Producer Seed Data--
INSERT INTO [dbo].[PRODUCERS] (PRODUCERNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Karan','M','2018-09-20','Film Producer in india')
INSERT INTO [dbo].[PRODUCERS] (PRODUCERNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Yash','M','2018-09-22','Film Producer in india')
INSERT INTO [dbo].[PRODUCERS] (PRODUCERNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Aditya','M','2018-09-20','Film Producer in india')
--End Producer Seed Data--

--Actor List--
INSERT INTO [dbo].[ACTORS] (ACTORNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Ajay','M','2008-09-20','Film actor in india')
INSERT INTO [dbo].[ACTORS] (ACTORNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Akshay','M','2008-09-20','Film actor in india')
INSERT INTO [dbo].[ACTORS] (ACTORNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Hrithik','M','2008-09-20','Film actor in india')
INSERT INTO [dbo].[ACTORS] (ACTORNAME,GENDER,DATEOFBIRTH,BIO) VALUES ('Salmaan','M','2008-09-20','Film actor in india')

--Movie List--
INSERT INTO [dbo].[MOVIES] (MOVIENAME,DATEOFRELEASE,PLOT,POSTER) VALUES ('Welcome','2018-09-20 00:00:00.000','Commedy and Action','welcome.jpeg')
INSERT INTO [dbo].[MOVIES] (MOVIENAME,DATEOFRELEASE,PLOT,POSTER) VALUES ('Batti Gul Meter Chaloo','2018-09-20 00:00:00.000','Drama','bgmc.jpeg')
INSERT INTO [dbo].[MOVIES] (MOVIENAME,DATEOFRELEASE,PLOT,POSTER) VALUES ('Golmaal','2018-09-20 00:00:00.000','Commedy and Action','Golmaal.jpeg')